---
- name: Install docker
  yum: 
    name: docker
    state: latest
  notify: restart docker service

- name: restart the docker
  service: 
    name: docker
    state: restarted

- name: set bridged network for container to communicate to each other
  command: docker network create brdgnet1
  ignore_errors: yes
  #clone

